site_name: ML Quality Model
theme: material
nav:
  - 'README.md'
  - 'characteristics.md'
  - 'definitions.md'
  - 'subcharacteristics.md'
  - 'schemas.md'
  - 'glossary.md'
  - 'license.md'
copyright: Copyright &copy; 1996–2021 Booking.com&trade;. All rights reserved. Published under the Creative Commons Attribution-NonCommercial 4.0 International License.
